# Here you can specify default options for TinyMCE across all controllers
#
# theme: advanced
# plugins:
#  - table
#  - fullscreen
theme: advanced
theme_advanced_toolbar_location: top
theme_advanced_buttons1:
- formatselect
- bold
- italic
- underline
- strikethrough
- separator
- justifyleft
- justifycenter
- justifyright
- justifyfull
- separator
- bullist
- numlist
- separator
- outdent
- indent
- separator
- link
- unlink
- image
- code
theme_advanced_buttons2: ''
theme_advanced_buttons3: ''
